[package]
name = "letsencrypt-rs"
description = "Easy to use Let's Encrypt client to issue and renew TLS certs"
version = "0.0.0"
authors = ["Onur Aslan <onur@onur.im>"]
license = "MIT"
keywords = ["letsencrypt", "acme"]
readme = "README.md"
documentation = "https://docs.rs/acme-client"
repository = "https://github.com/onur/letsencrypt-rs"

[dependencies]
